"""feature engineering: indicators, timing guards, and transforms."""

from quantauto.features.engineering import (
    AVAILABLE_FEATURES,
    CustomFeatureSpec,
    EngineeredFeatures,
    FeatureSpec,
    build_features,
    build_multi_asset_features,
    calculate_atr,
    calculate_bollinger_bands,
    calculate_close_position,
    calculate_ema,
    calculate_high_low_range,
    calculate_log_returns,
    calculate_macd,
    calculate_obv,
    calculate_rate_of_change,
    calculate_returns,
    calculate_rolling_std,
    calculate_rolling_zscore,
    calculate_rsi,
    calculate_sma,
    calculate_volume_ratio,
)
from quantauto.features.presets import (
    BASE_PRESET_SPECS,
    DEFAULT_PRESET,
    build_multi_preset_features,
    build_preset_features,
    custom_fits_columns,
    expand_preset_specs,
    filter_custom_to_loaded,
    filter_specs_to_loaded,
    make_custom_feature,
    make_preset_specs,
    spec_fits_columns,
)
from quantauto.features.timing import (
    FeatureMeta,
    apply_execution_shift,
    check_no_lookahead,
    get_valid_start,
    get_warmup_mask,
)
from quantauto.features.transforms import (
    align_features_to_source,
    cross_sectional_rank,
    cross_sectional_zscore,
    drop_warmup,
    forward_fill,
    minmax_scale,
    winsorize,
    zscore_normalize,
)

__all__ = [
    # engineering — indicators
    "calculate_returns",
    "calculate_log_returns",
    "calculate_sma",
    "calculate_ema",
    "calculate_rolling_std",
    "calculate_rolling_zscore",
    "calculate_rate_of_change",
    "calculate_rsi",
    "calculate_macd",
    "calculate_bollinger_bands",
    "calculate_atr",
    "calculate_obv",
    "calculate_volume_ratio",
    "calculate_high_low_range",
    "calculate_close_position",
    # engineering — batch builder
    "FeatureSpec",
    "CustomFeatureSpec",
    "EngineeredFeatures",
    "AVAILABLE_FEATURES",
    "build_features",
    "build_multi_asset_features",
    "DEFAULT_PRESET",
    "BASE_PRESET_SPECS",
    "expand_preset_specs",
    "make_preset_specs",
    "make_custom_feature",
    "spec_fits_columns",
    "custom_fits_columns",
    "filter_specs_to_loaded",
    "filter_custom_to_loaded",
    "build_preset_features",
    "build_multi_preset_features",
    # timing
    "FeatureMeta",
    "get_warmup_mask",
    "get_valid_start",
    "check_no_lookahead",
    "apply_execution_shift",
    # transforms
    "zscore_normalize",
    "minmax_scale",
    "winsorize",
    "forward_fill",
    "drop_warmup",
    "cross_sectional_zscore",
    "cross_sectional_rank",
    "align_features_to_source",
]
